package com.example.VaccineManagementSystem.Models;

import com.example.VaccineManagementSystem.Enums.Gender;
import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;

@Table(name="users") //Name of table
@Entity
@Data
public class User {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY) //For autogenerated id and Primary Key
    private int userId;

    @Column(name="userName") //Specified column name
    private String name;

    @Column(unique = true) //Unique Key
    private String email;

    @Enumerated(value = EnumType.STRING) //Also works: @Enumerated(EnumType.STRING)
    private Gender gender;

    private int age;
    private String mobile;

    //Bidirectional Mapping
    @JsonIgnore
    @OneToOne(mappedBy = "user", cascade = CascadeType.ALL)
    private Dose dose;

    @JsonIgnore
    @OneToMany(mappedBy = "user", cascade = CascadeType.ALL)
    private List<Appointment> appointmentList=new ArrayList<>();
}
